// <auto-generated />
using System;
using HephaestusSQLiteRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HephaestusSQLiteRepo.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20210131145408_fix_foucsTask_wrong_timezone")]
    partial class fix_foucsTask_wrong_timezone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("HephaestusSQLiteRepo.Entities.FocusTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FocusTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
